# Generated by Django 3.2.3 on 2021-06-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
    ]
