# Generated by Django 3.2.3 on 2021-06-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_appointment_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_available',
        ),
    ]
