# Generated by Django 3.2.3 on 2021-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailibity',
            name='is_reserverd',
            field=models.BooleanField(null=True),
        ),
    ]
