# Generated by Django 3.2.3 on 2021-06-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_rename_is_reserverd_doctoravailibity_is_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailibity',
            name='is_reserved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
